version: "3.9"
services:
  node-1:
    image: postgres:14.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres # default) postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chinook
    volumes:
      - ./share:/opt
